codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "65...100"

  status:
    project:
      default:
        target: 65%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "header, diff, changes, tree, flags"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: false

ignore:
  - "**/*_test.go"
  - "**/*.pb.go"
  - "**/mock_*.go"
  - "cmd/**/*.go"
  - "web/**/*"
  - "docs/**/*"
